### PR TITLE
Fixed issue with hashed out resolveurl

### PR DESCRIPTION
**Pull request by catchup4kodi**

### CODE REVIEW

**Comment by catchup4kodi** [comment]
ok now its fixed

**Comment by jsergio123** [comment]
So now is ResolveUrl a fork of the UrlResolver or the UrlResolver a fork of ResolveUrl? ;)

**Comment by catchup4kodi** [comment]
elgantly aligned :1st_place_medal:  unsure lol

**Comment by jsergio123** [comment]
There are some issues. You missing other changes in the core code and you didn't change the paths for the auto update plugins. These will cause smu to break. Honestly I think it would be easier to just fork resolveurl back to urlresolver. Good luck

**Comment by jsergio123** [comment]
I hope my last comment didn't sound like. I was being an ass. I really meant good luck and was trying to give you advice.

**Pull request closed without merging**
