### PR TITLE
Update speedvid.py

### PR DESCRIPTION
**Pull request by mbebe**
remove speedvid_gmu
fix regex

### CODE REVIEW

**Comment by tvaddonsco** [comment]
Please confirm that you have tested this carefully!

**Comment by azzy9** [comment]
not sure why the GMU is being removed, but if it has to go the speedvid_gmu.py file should be removed as well.

**Comment by tvaddonsco** [comment]
Can you please resubmit this fix without needing to remove GMU so that it can be updated on the fly? @mbebe

**Comment by tvaddonsco** [comment]
Can you please resubmit this fix without needing to remove GMU so that it can be updated on the fly? @mbebe

**Pull request closed without merging**
